### PR TITLE
Remove redundant cancel button appearing when adding activities on plans form

### LINKED ISSUE #1587: Edit certain fields in draft makes page unresponsive- Thai Preview
@Eric Musyoka cc @Kang'a so quick feedback:
TEST: Ability to add/remove activities in C.T.P:
This functionality works where one can add /remove the activities.
However, I noticed that if I wanted to remove all activities and and add just one, the page shows Added these activities(shows all). If I click on one of the activities I want to add and click the X button, the page hangs. See image below. https://web.reveal-th-preview.smartregister.org/plans/update/40223877-5fc9-4978-a782-32c6cf72fefe
Trying to test if this is happening due to the google translate extension
I checked to see if it was the translate, it is not. The page is unresponsive unless I select all activities.
https://github.com/onaio/reveal-frontend/issues/1378
image

### PR DESCRIPTION
**Pull request by ciremusyoka**
Closes #1587 
The modal for adding activities had two cancel button one of which was unresponsive. This pr removes the redundant cancel button caught [here](https://github.com/onaio/reveal-frontend/pull/1596#issuecomment-848881314).

Screenshot
Screenshot from 2021-05-27 10-10-30

### CODE REVIEW

**Review by moshthepitt — CHANGES_REQUESTED** [review]
Should we have a test for this?

**Comment by ciremusyoka** [comment]
> Should we have a test for this?

@moshthepitt this particular code was not tested and since am removing it nothing should change on the tests.

**Review by moshthepitt — DISMISSED** [review]
Going to approve but note that:

> @moshthepitt this particular code was not tested and since am removing it nothing should change on the tests.

There is no regression test to guard against somehow re-introducing this

**Comment by ciremusyoka** [comment]
> There is no regression test to guard against somehow re-introducing this

@moshthepitt a quick test [here](https://github.com/onaio/reveal-frontend/pull/1602#pullrequestreview-670969113) to ensure we only have one cancel button.

**Review by moshthepitt — APPROVED** [review]

**Review by kelvin-muchiri — APPROVED** [review]

**Comment by Naima-Bashir** [comment]
this has passed qa on both Thai Preview and stage

**Pull request merged**
