### PR TITLE
Indicate plans displayed are for the applied user filter only

### PR DESCRIPTION
**Pull request by ciremusyoka**
Part of https://github.com/OpenSRP/opensrp-client-reveal/issues/1024

Adds a text when the user filter is applied specifying the plans listed are ones assigned to the named user only.

### CODE REVIEW

**Comment by ciremusyoka** [comment]
Screenshot from 2020-09-17 18-08-29

**Review by moshthepitt — DISMISSED** [review]

**Comment by p-netm** [comment]
@moshthepitt @ciremusyoka should we use some sort of UX to show this. sth like showing the userFilter and any other control as being active by use of color.

**Comment by moshthepitt** [comment]
@p-netm sounds like a good idea.  What did you have in mind?

**Comment by p-netm** [comment]
> @p-netm sounds like a good idea. What did you have in mind?

@moshthepitt @ciremusyoka  The filter buttons can change appearance when they are active, say sth like :
image

**Comment by moshthepitt** [comment]
I  like it

**Comment by ciremusyoka** [comment]
user filter on
userfilter
row height filter on
rowHeight
column filters on
columnfilters
all filters on
allFilters

**Review by moshthepitt — APPROVED** [review]

**Review by p-netm — APPROVED** [review]
:+1:

**Pull request merged**
