### PR TITLE
Disable high level jurisdictions team assignment

### PR DESCRIPTION
**Pull request by p-netm**
Disable high level jurisdictions team assignment

### CODE REVIEW

**Comment by moshthepitt** [comment]
@p-netm how do you feel about leaving the code "as is" and ensuring this `REACT_APP_SHOW_TEAM_ASSIGN_ON_OPERATIONAL_AREAS_ONLY` is turned to the right value?

**Comment by p-netm** [comment]
> @p-netm how do you feel about leaving the code "as is" and ensuring this `REACT_APP_SHOW_TEAM_ASSIGN_ON_OPERATIONAL_AREAS_ONLY` is turned to the right value?

depends on if the intention was to still have `assignments at non-leaf nodes levels` behaviour configurable for certain envirionments.

**Comment by moshthepitt** [comment]
signments at non-leaf nodes levels isn't expected to happen at any of our environments.  But I wonder whether it is something that we should keep because there is a chance that we may want it in the future, or some other non-reveal implementation may want it

**Comment by p-netm** [comment]
> signments at non-leaf nodes levels isn't expected to happen at any of our environments. But I wonder whether it is something that we should keep because there is a chance that we may want it in the future, or some other non-reveal implementation may want it

ok, closing this. will switch the env everywhere to false

**Pull request closed without merging**
