### PR TITLE
Displays organizaitonSelect dropdown in visible space

### LINKED ISSUE #537: IRS Plan-Jurisdiction Assignment Cleanup
There are some bugs which need to be addressed with the UI involved with assigning organizations to plan-jurisdictions for IRS plans.

- [ ] **Popover and Dropdown should not go below the page**
scroll

- [x] **Page title should not have prepending comma**
Screenshot from 2019-10-16 17-59-15

### PR DESCRIPTION
**Pull request by p-netm**
Automatically chooses the direction in which the overaly(dropdown
in the select ) opens up so that it is visible to users.

closes #537

### CODE REVIEW

**Comment by p-netm** [comment]
assugnment

**Comment by p-netm** [comment]
I however dont know if this is what we want:
image

**Comment by p-netm** [comment]
> I however dont know if this is what we want:
> image

@moshthepitt What do you think of this.

**Comment by moshthepitt** [comment]
@p-netm the modals/popups seem layered on top of each other.  Is this how it always is?

**Comment by p-netm** [comment]
> @p-netm the modals/popups seem layered on top of each other. Is this how it always is?

@moshthepitt yes, I take i should also change that?

**Comment by moshthepitt** [comment]
Yes please @p-netm

**Comment by moshthepitt** [comment]
Was superseded by https://github.com/onaio/reveal-frontend/pull/929

**Pull request closed without merging**
