### PR TITLE
Fix submit button remaining disabled on adding new activities when editing plan

### LINKED ISSUE #1587: Edit certain fields in draft makes page unresponsive- Thai Preview
@Eric Musyoka cc @Kang'a so quick feedback:
TEST: Ability to add/remove activities in C.T.P:
This functionality works where one can add /remove the activities.
However, I noticed that if I wanted to remove all activities and and add just one, the page shows Added these activities(shows all). If I click on one of the activities I want to add and click the X button, the page hangs. See image below. https://web.reveal-th-preview.smartregister.org/plans/update/40223877-5fc9-4978-a782-32c6cf72fefe
Trying to test if this is happening due to the google translate extension
I checked to see if it was the translate, it is not. The page is unresponsive unless I select all activities.
https://github.com/onaio/reveal-frontend/issues/1378
image

### PR DESCRIPTION
**Pull request by ciremusyoka**
Closes #1587
Formik was not evaluating validity of the plans form on pushing new activity to the activities array. The fix was to use `setFieldValue` instead of push.

### CODE REVIEW

**Review by moshthepitt — APPROVED** [review]

**Review by haseemVD — APPROVED** [review]

**Comment by Naima-Bashir** [comment]
Just confirming if the fix is for stage or thai or just one? @ciremusyoka 

For thai, the first button is still unresposive
image

**Comment by Naima-Bashir** [comment]
stage also has this extar button that is unresposive, perhaps we can remove it since the one of the far right works 
image

**Comment by ciremusyoka** [comment]
> Just confirming if the fix is for stage or thai or just one? @ciremusyoka
> 
> For thai, the first button is still unresposive
> image

This has only been deployed to stage not yet to Thai preview.

**Comment by Naima-Bashir** [comment]
PASSED QA

**Pull request merged**
