### PR TITLE
[DNM] 338 disabling plan form fields

### PR DESCRIPTION
**Pull request by cKellyDesign**
For #338

### CODE REVIEW

**Comment by moshthepitt** [comment]
@cKellyDesign 

The `ActionReasonType` only allows 'Investigation', and 'Routine' while `FIReasonType` allows only 'Routine', and 'Case Triggered'.  Can we get confirmation that these two fields do indeed hold exactly the same kind of data?

**Comment by cKellyDesign** [comment]
> The ActionReasonType only allows 'Investigation', and 'Routine' while FIReasonType allows only 'Routine', and 'Case Triggered'. 

@moshthepitt The relation between Plans, Activities/Tasks, and Goals is where I usually get very confused.

> Can we get confirmation that these two fields do indeed hold exactly the same kind of data?

cc @craigappl @githengi @mberg

**Comment by cKellyDesign** [comment]
> The ActionReasonType only allows 'Investigation', and 'Routine' while FIReasonType allows only 'Routine', and 'Case Triggered'.

@moshthepitt is this the same type of content being discussed here (👉  https://github.com/onaio/reveal-frontend/issues/288#issuecomment-521534421) or is something else?

**Comment by cKellyDesign** [comment]
@mberg with the recent changes from adding the Edit FI PlanForm page, the tests which are failing here are indicating that my method of disabling certain fields isn't really congruent anymore. Since this was a pretty aesthetic for-the-demo request, I'm going ask that we don't do this and close the PR instead of trying to merge it (just to undo it later).

**Pull request closed without merging**
