### PR TITLE
Fix irs reporting

### PR DESCRIPTION
**Pull request by p-netm**
Resolves issues reported [here](https://onaio.slack.com/archives/CBSU8L2SC/p1596514793200300)

### CODE REVIEW

**Comment by moshthepitt** [comment]
@p-netm which of those issues does it resolve?  Could you get screenshots in this issue?

**Comment by p-netm** [comment]
@moshthepitt  these are the addressed issues so far: 2 out of 3
| image | 
|:--:| 
| *the name column has overlapping values* |


| image (1)| 
|:--:| 
| *There's another issue with the percentages. It looks like they're calculating  "Structures remaining to spray to reach 90% SE. It looks like that's displaying a percentage, but it should be a whole number. * |

**Comment by moshthepitt** [comment]
Thanks @p-netm.  Could you fix this "Structures remaining to spray to reach 90% SE"?

**Comment by p-netm** [comment]
Tests for the changes included here:
- the drill-down in the genericJurisdictionReport component is able to consume `ZambiaFocusAreas2019` columns correctly
- an "integration test" for the IRS reporting map
    - the service calls.
    - the relevant props passed to the map wrapper component.
    - params during selector's invocation.
Both these tests are proving to be more involved than the time available at the moment allows for. I am moving them into a a different issue #1105

**Pull request merged**
