### PR TITLE
remove legend from adverse reaction col

### PR DESCRIPTION
**Pull request by haseemVD**
This PR addresses issue #1591 

Screenshot 2021-05-17 at 12 02 00 PM

### CODE REVIEW

**Comment by haseemVD** [comment]
@samkanga Please find the attached screenshot and let me know if thats okay.

**Comment by samkanga** [comment]
@haseemVD the shared screenshot looks OK. Thank you.

**Comment by moshthepitt** [comment]
@haseemVD is it possible to have a test for this?

**Comment by haseemVD** [comment]
> @haseemVD is it possible to have a test for this?

@moshthepitt test to check the background color ?

**Comment by haseemVD** [comment]
> @haseemVD is it possible to have a test for this?

Updated test to check if right function is called to fetch values.

**Review by moshthepitt — APPROVED** [review]

**Review by p-netm — APPROVED** [review]

**Pull request merged**
