### PR TITLE
Exclude src/index.tsx from the coverage report

### LINKED ISSUE #671: Increase test coverage for src/index.tsx
Increase test coverage to be >= 85% for:

`src/index.tsx`

Part of #658

### PR DESCRIPTION
**Pull request by DavisRayM**
# Changes proposed in this PR

- Exclude `src/index.tsx` from the coverage report

Closes #671

### CODE REVIEW

**Comment by moshthepitt** [comment]
@DavisRayM was the change in circle ci configs necessary?

**Comment by DavisRayM** [comment]
> @DavisRayM was the change in circle ci configs necessary?

I'm not quite sure, trying out an alternate option (setting the jest configuration in `package.json`).

**Comment by DavisRayM** [comment]
> @DavisRayM was the change in circle ci configs necessary?

It's not necessary, the change in the `package.json` is more than enough to exclude the `index.tsx` from the coverage report. I've made the change in the latest commit.

**Comment by moshthepitt** [comment]
I mean that it looks like you already have tests.  Is it necessary to go ahead and still exclude the file from coverage?

**Comment by DavisRayM** [comment]
> I mean that it looks like you already have tests. Is it necessary to go ahead and still exclude the file from coverage?

The test I've written doesn't execute any code within `index.tsx` as such the coverage isn't affected at all. (It'll still be 0% with my test)

**Comment by moshthepitt** [comment]
> The test I've written doesn't execute any code within index.tsx as such the coverage isn't affected at all. (It'll still be 0% with my test)

Cool, understood

**Comment by DavisRayM** [comment]
> > The test I've written doesn't execute any code within index.tsx as such the coverage isn't affected at all. (It'll still be 0% with my test)
> 
> Cool, understood

Yea, 😅 I'm not quite sure if there is a better way to test the `index.tsx` at this point. But I can add a `DNM` tag for now while I research a bit more.

**Comment by DavisRayM** [comment]
I haven't been able to find any alternative to the current implementation.... I think it would be better to remove the `index.tsx` file from the coverage report and forgo the test.

CC: @moshthepitt

**Comment by moshthepitt** [comment]
@DavisRayM sounds good to me

**Comment by DavisRayM** [comment]
> @DavisRayM sounds good to me

Nice, I've dropped the commit that added the test. This PR should now be excluding the `src/index.tsx` from the coverage report.

**Pull request merged**
