### PR TITLE
Add planning tool view

### PR DESCRIPTION
**Pull request by p-netm**
part of #892 #838 
- Adds planning page
- Makes some changes to the plan form views to support new useCase

### CODE REVIEW

**Comment by moshthepitt** [comment]
Draft_plans_Reveal

**Comment by moshthepitt** [comment]
@p-netm might be tired, but I am having trouble understanding:

- the way the code is organized and 
- the deleted files

Lets have a call to talk about those

**Comment by p-netm** [comment]
> Create_New_Plan_Reveal


> Create_New_Plan_Reveal

This is now only shown when coming from the Manage plans add button link.

**Comment by Naima-Bashir** [comment]
How to test: drill down at the assign page and planning tool then back the breadcrumbs

**Comment by Naima-Bashir** [comment]
tested this.
It works as expected. Only thing I noticed is this: https://github.com/onaio/reveal-frontend/issues/993
It could be a bug but let's discuss
cc @moshthepitt @p-netm @samkanga

**Pull request merged**
