### PR TITLE
{DNM} Add cookie Jar to express

### LINKED ISSUE #768: Reveal Thailand Production session 500 error
We're getting the following error code when trying to login to the thailand production environment through the web UI:

```
{
message: "The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.",
status: "error",
statusCode: 500
}
```

### Triaging the problem
1 Starting with just the google analytics cookies on web.reveal-th
image

2 Click OpenSRP button which redirects to https://reveal-th.smartregister.org/opensrp/login.jsp
Five cookies in use
Two for google analytics
reveal-th.smartregister.org
- AWSALB: lQ6z+3mOJ0Rxx4aMJHe/Aan6MlGNfqdr9Ingn0c
- AWSALBCORS: lQ6z+3mOJ0Rxx4aMJHe/Aan6MlGNfqdr9Ingn0c
- JSESSIONID: 85302A2412074B69EDC3F61635E4EFD7

3 I enter the username and password and click login. I'm redirected to the OAuth Approval view
https://reveal-th.smartregister.org/opensrp/oauth/authorize?client_id=52vjwavfeLkMxZArGorgAoExwicfDGb49rVy&redirect_uri=https%3A%2F%2Fweb.reveal-th.smartregister.org%2Foauth%2Fcallback%2FOpenSRP%2F&scope=read%20write&response_type=code&state=opensrp
Five cookies in use
Two for google analytics
reveal-th.smartregister.org
- AWSALB: g+D58fHD44XeKLLh+J0qxR6PWu1eSNqm2cY/Fum7Z2OWkF1pPl6DpnsKb5rJWemMhw+eiT/0PcvR69QZ0m7Y1xzDeeq0cEWzH99HiT0IC8wk7q0F5y2wUQVtSV8e
- AWSALBCORS: g+D58fHD44XeKLLh+J0qxR6PWu1eSNqm2cY/Fum7Z2OWkF1pPl6DpnsKb5rJWemMhw+eiT/0PcvR69QZ0m7Y1xzDeeq0cEWzH99HiT0IC8wk7q0F5y2wUQVtSV8e
- JSESSIONID: 3319974A520925A41DED81C3899B242F
(Note that the JSESSIONID changed

4 Click Authorize and I successfully redirect to the web UI
image
Seven Cookies in use
Three for google analytics
reveal-th.smartregister.org
- AWSALB: 2cDmesfqZi0Z/JNkpM4568W9hQh7aLjck0jBExkMRfiuPQSrf6JXZiDcupi5uflUj+UidTxSD/O+JpHe76f/LzcnMBpSfBYu/NUyrtywbz+BqOCT+P6ync7ERROR
- AWSALBCORS: 2cDmesfqZi0Z/JNkpM4568W9hQh7aLjck0jBExkMRfiuPQSrf6JXZiDcupi5uflUj+UidTxSD/O+JpHe76f/LzcnMBpSfBYu/NUyrtywbz+BqOCT+P6ync7ERROR
- JSESSIONID: 3319974A520925A41DED81C3899B242F
Note, the Load balancer cookies changed, but not the JSESSIONID
web.reveal-th.smartregister.org
reveal-session: s%3APCfCshHxJQewrTYnPycyr2a1Jy-jqM3u.xxCkjNTwCdcvkHbKRTOxkMEertnbVSW5PVZrOMlsX7E

5 Now, we're going to logout.
Four Cookies are present
Three are from Google Analytics
web.reveal-th.smartregister.org
reveal-session:
s%3APCfCshHxJQewrTYnPycyr2a1Jy-jqM3u.xxCkjNTwCdcvkHbKRTOxkMEertnbVSW5PVZrOMlsX7E

6. Login again and everything works.
7 Remove the reveal-session cookie and try to login again. Everything works

----
At this point, it's all working. Now, we're going to remove the cookie from https://reveal-th.smartregister.org/opensrp/login.jsp to see if we can try to login again.

1 Login to the opensrp server 
Five cookies again, the same as before.

2 We get the OAuth Approval view again
https://reveal-th.smartregister.org/opensrp/oauth/authorize?client_id=52vjwavfeLkMxZArGorgAoExwicfDGb49rVy&redirect_uri=https%3A%2F%2Fweb.reveal-th.smartregister.org%2Foauth%2Fcallback%2FOpenSRP%2F&scope=read%20write&response_type=code&state=opensrp
Three cookies
- AWSALB: VSREPYtUMARI9R+h6aqid8jVDTlF0pHPfOa3BO74x9d2akjcCFiEueRdZodseAHxHKAePOnnX2lQEGfUbutcRECXkCI4+S93x2zgdvjJ0OBSy30tlZwjJsKmrB6D
- AWSALBCORS: VSREPYtUMARI9R+h6aqid8jVDTlF0pHPfOa3BO74x9d2akjcCFiEueRdZodseAHxHKAePOnnX2lQEGfUbutcRECXkCI4+S93x2zgdvjJ0OBSy30tlZwjJsKmrB6D
- JSESSIONID: 01C1C45D24A40AA25BFF71138A34A34F

3 Click Authorize and get the 500 error
https://web.reveal-th.smartregister.org/oauth/callback/OpenSRP/?code=bV3E2d&state=opensrp
Three Cookies
- AWSALB: 6cJy/FXPB2oFg1uOjnrzYkWVsTrOo2wyyiJjN8wNEvEk0CC6iWWkO6gFLoGvuJO0a5k1yWuC8tqweOm44E4uJMqz/n/mpT/D4w9rsJ1BFGTmzcIauco0ovdxEtLe
- AWSALBCORS: 6cJy/FXPB2oFg1uOjnrzYkWVsTrOo2wyyiJjN8wNEvEk0CC6iWWkO6gFLoGvuJO0a5k1yWuC8tqweOm44E4uJMqz/n/mpT/D4w9rsJ1BFGTmzcIauco0ovdxEtLe
- JSESSIONID: 01C1C45D24A40AA25BFF71138A34A34F
(Note, different load balancer than the one that was authorized.)

----
Now, we're going to close the incognito window and try the whole thing over again.
U7PVLYBXkX5nNji6vhno5i7HCHsxlpWSm73dApsQmsalG6BC2QmdkE77KDXWkIYbUAtJzTnEz2V63YOU3CYysSbODpPTSjj8+UzXfSvXKpTX1Oxw3UUoUsfc+h6x
2C09D69CC98CC97951AE2FFE8BCB2617

It gave the 500 error when logging in with the same credentials
New session id and new Load Balancer cookies

----
Now, we're going to close out the incognito window and login as a different user.

This returns the 500 error.

----
Now, we're going to look at the auth redirect_URI
URL redirected to: https://web.reveal-th.smartregister.org/oauth/callback/OpenSRP/?code=R7vgl7&state=opensrp
Authorization redirect URI: redirect_uri=https://web.reveal-th.smartregister.org/oauth/callback/OpenSRP/

They appear to be the same and it's correct in the inventory
----
I waited 30 minutes and it worked again.
----
Now, I'm going to check the oauth/state when successfully logged in
https://web.reveal-th.smartregister.org/oauth/state

{"gatekeeper":{"success":true,"result":{"userName":"removed","roles":["System Developer","OpenSRP: Get All Events","Administrator","Provider"],"preferredName":"Craig Appl","oAuth2Data":{"access_token":"44b67744-d56d-46ad-8e4f-379dc0b2d67d","token_type":"bearer","refresh_token":"7eb49c5e-bd48-424f-abb6-a552cd4dd797","expires_in":3495,"scope":"read write"}}},"session":{"authenticated":true,"extraData":{"userName":"removed","roles":["System Developer","OpenSRP: Get All Events","Administrator","Provider"],"preferredName":"removed","oAuth2Data":{"access_token":"44b67744-d56d-46ad-8e4f-379dc0b2d67d","token_type":"bearer","refresh_token":"7eb49c5e-bd48-424f-abb6-a552cd4dd797","expires_in":3495,"scope":"read write"}},"user":{"email":"","gravatar":"","name":"","username":"removed"}}}

When I logout of the web UI, the state changes successfully.

----
### Observations.
1. It's not clear what the problem is.
2. When you login separately to the OpenSRP server without going to the web UI, it fails every time and stays in the failed state for a while. If you wait 30-60 minutes it seems like you can login again without a problem.
3. The error also comes when you clear the cookie on the OpenSRP server and try to login again through the browser. It doesn't matter which user you try to login again as after the error has occurred, no one else can login. It's like the error is causing a blockage for all subsequent logins.
4. I'm guessing that if you wait 3600 seconds (60 minutes) the original token expires and it works again.

### LINKED ISSUE #770: Test Reaveal-th login using a cooking jar
related to #768 .
and using this link: https://stackoverflow.com/a/19937138

### PR DESCRIPTION
**Pull request by p-netm**
close #768 close #770 
Adds a "pre-flight" request in the callback handler a cookie jar.
So from the above request we can then extract all cookies from `reveal-th.smartregister` including the load balancer cookies, save those in a cookie jar and apply them to all other requests to `reveal-th.smartregister`

### CODE REVIEW

**Comment by p-netm** [comment]
I hope to test this on `reveal-th.smartregister` before bundling in release, will update here once I do.

**Comment by moshthepitt** [comment]
@p-netm should we close this and the underlying issues?  We might need to create an issue on the [OpenSRP repo](https://github.com/OpenSRP/opensrp-server-web).

**Comment by p-netm** [comment]
> @p-netm should we close this and the underlying issues? We might need to create an issue on the [OpenSRP repo](https://github.com/OpenSRP/opensrp-server-web).

I suppose we need to create the issue on OpenSRP, but I would also like to have another look at this and try to understand why this failed.

**Comment by moshthepitt** [comment]
Cool.

**Comment by moshthepitt** [comment]
@p-netm should we close this?

**Comment by moshthepitt** [comment]
Going to close this.

**Pull request closed without merging**
