### PR TITLE
Issue # progress indicators visualizations

### PR DESCRIPTION
**Pull request by p-netm**
adds a marker on the progress bar that shows the target value.
modifies the goal reporting to be completed tasks of total_tasks

progressIndicators

### CODE REVIEW

**Comment by p-netm** [comment]
withData

**Comment by p-netm** [comment]
> modifies the goal reporting to be completed tasks of total_tasks

@moshthepitt @cKellyDesign Is this still the correct logic?, In master we have completed_tasks of target_value which would then mean we do not really need the marker, right?

**Comment by moshthepitt** [comment]
@p-netm lets shelve this until @samkanga and @craigappl define the requirement better.

**Comment by moshthepitt** [comment]
@p-netm closing this as it doesn't seem like we'll be able to merge it any time soon.

**Pull request closed without merging**
