### PR TITLE
Update jurisdiction matadata payload

### LINKED ISSUE #1337: Duplicates when Downloading Jurisdiction Metadata on Namibia Production
- [ ] We previously had an issue where we got duplicates when downloading jurisdiction meta data on targets on Namibia Production. This was resolved and had been working OK. However, the issue appears to have recurred as shown on the screenshot below of a document that I downloaded.

image

### PR DESCRIPTION
**Pull request by ciremusyoka**
Fixes #1337 
Adds a document _id key and a UUID key for each setting.

### CODE REVIEW

**Comment by ciremusyoka** [comment]
Sample payload
```json
{
  "settingConfigurations": [
    {
      "_id": "fc17ac3e-ffea-55d4-902c-3069d675c198",
      "identifier": "jurisdiction_metadata-population",
      "settings": [
        {
          "description": "Jurisdiction Metadata for Zambia(vl 2020) metadata id ecfbf048-fb7a-47d8-a12b-61bf5d2a6e7b",
          "key": "ecfbf048-fb7a-47d8-a12b-61bf5d2a6e7b",
          "label": "Zambia(vl 2020) metadata",
          "uuid": "f6b149d4-1a9a-54a1-81f8-7c7e22b297b0",
          "value": "2000"
        }
      ],
      "type": "SettingConfiguration"
    }
  ]
}
```

**Comment by moshthepitt** [comment]
@ciremusyoka first time uploads and re-uploads of the same jurisdictions works?

**Comment by ciremusyoka** [comment]
> @ciremusyoka first time uploads and re-uploads of the same jurisdictions works?

Yes it works

**Review by moshthepitt — APPROVED** [review]
Nice work

**Comment by moshthepitt** [comment]
Please ask @dubdabasoduba to take a look

**Comment by dubdabasoduba** [comment]
> > @ciremusyoka first time uploads and re-uploads of the same jurisdictions works?
> 
> Yes it works

Tested this on the review server right?

**Comment by ciremusyoka** [comment]
> > > @ciremusyoka first time uploads and re-uploads of the same jurisdictions works?
> > 
> > 
> > Yes it works
> 
> Tested this on the review server right? The payload looks good. Nice work

I tested on reveal stage server

**Review by pld — APPROVED** [review]
lgtm

**Pull request merged**
